spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_database
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

jwt:
  secret: MYJWTSECRET
  expiration: 3600000
